experiment:
    id: leaf_segmentation
##Data
data:
    resolution: 0.001
    sample_size: 40000
    batch_size_embed: 1
    batch_size_confid: 4
    accumulate_grad: 1
    eval_n_samples: 30000
    min_leaf_point_ratio_inference: 0.01
    min_samples_hdbscan_ratio: 1.0
    min_leaf_area: 1
    augment: True
    patches: True
    discard_unlabeled: False
    # percent of discarded instances
    confid_filter_thres: 0.70
    only_labeled: False
    confid_data_samples: 100000

##Training
train:
    n_gpus: [0,]
    num_workers: 15
    max_epoch: 500
    max_embed_steps: 10000000
    max_confid_steps: 10000000
    lr_emb: 1e-4
    lr_confid: 1e-4
    warmup_epochs: 0
    check_val_every_n_epoch: 1
    val_metric: 'PQ_leaf'
    val_metric_min_max: 'max'

##Network
offset_model:
    enable_leaves: True
    enable_plants: False
    plant_offset_size: 2
    decoder_type: 'deconvolution'
    layer_norm: False
    use_poses_as_feats: True
    decoder_unary: True
    loss: 'offset'
    enable_dropout: False
    grid_sampling_method: 'mean'
    # min_kernel_r: 0.01
    max_kernel_r: 0.08
    num_enc_layers: 9
    enc_layer_downsample: [1,0,1,0,1,0,1,0,0]
    # n_downsamplings: 7
    min_feat_size: 64
    max_feat_size: 256
    conv_r2s_gain: 1.5
    kp_enabled: False
    pos_enc: False

confid_model:
    grid_sampling_method: 'mean'
    use_emb_feats: True
    mask_injection: False
    enable_dropout: False
    input_size: 3
    output_size: 1
    # min_kernel_r: 0.005
    max_kernel_r: 0.07
    num_enc_layers: 9
    enc_layer_downsample: [1,0,1,0,1,0,1,0,0]
    layer_rotinv: [0,0,0,0,0,0,0,0,0,0,0]
    n_downsamplings: 7
    min_feat_size: 32
    max_feat_size: 128
    conv_r2s_gain: 1.5
    confid_weight: 1.0
    final_sigmoid: True

debug:
    max_render_freq: 100
    overfit: False
